add commments in post
ShivanshSinghnnovative/socialappfirebase pull request #10
Opened 2023-11-18 13:54 UTC by ShivanshSinghnnovative

2023-11-20 13:43 UTC, yuvrajInno commented on src/store/post-store.js
> +    let posts = []
use state for these

2023-11-20 13:43 UTC, yuvrajInno commented on src/store/post-store.js
> +    const postComment = async (commentText, postId) => {
change function name

2023-11-20 13:44 UTC, yuvrajInno commented on src/store/post-store.js
> +            console
remove these

2023-11-20 13:47 UTC, yuvrajInno commented on src/store/post-store.js
> +                console.log("Comment updated successfully");
remove unnecessary consoles

2023-11-20 13:50 UTC, yuvrajInno commented on src/pages/showPost.vue
> +                        @click=" (comment[post.id] && editableCommentId[post.id] ? handelupdateComment(comment[post.id], post.id) : postCommentHandle(post.id))"
change function name

2023-11-20 13:52 UTC, yuvrajInno commented on src/pages/showPost.vue
> +const comments = ref({});
change name to postCommentList

2023-11-20 13:55 UTC, yuvrajInno commented on src/pages/showPost.vue
> +const handelupdateComment = async (updateExistingComment, postId) => {
add trim function

2023-11-22 07:37 UTC, meanstack9716 requested changes

2023-11-22 07:37 UTC, meanstack9716 commented on src/store/post-store.js
> +            const commentTitle = commentText;
do you really need this const commentTitle = commentText;?
you can directly change variable name in argument declaration @ShivanshSinghnnovative

2023-11-22 07:55 UTC, meanstack9716 requested changes

2023-11-22 07:55 UTC, meanstack9716 commented on src/store/post-store.js
> +            const querySnapshot = await getDocs(query(userDetailsCollection, where("createdAt", "==", createdAt)));
why are you using createdAt  for where clause? do you not have the comment UUID? @ShivanshSinghnnovative

2023-11-22 07:55 UTC, meanstack9716 commented on src/store/post-store.js
> +            const userDetailsCollection = collection(db, `post/${postId}/comment`);
why comment collection names on userDetailsCollection? @ShivanshSinghnnovative

2023-11-22 09:20 UTC, merged